
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '../styles/main.scss';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




const RootLayout: React.FC<Readonly<{ children: React.ReactNode }>> = ({ children }) => {

  return (

    <html lang="fr">

      <body className={`home`}>

        <main className="wrapper">{children}</main>

      </body>
    </html>

  );

}
export default RootLayout;

